---
# file: tasks/main.yml
# Reset locale to default.
#
# @see http://askubuntu.com/questions/144235/locale-variables-have-no-effect-in-remote-shell-perl-warning-setting-locale-f
#

- name: install package locales
  apt: name=locales state=present
  when: ansible_pkg_mgr == "apt"

- name: create locales
  locale_gen: name={{ locale }} state=present
  when: ansible_os_family == "Debian"

- name: update-locale
  command: update-locale LC_ALL={{ locale }} LANG={{ locale }}
  when: ansible_os_family == "Debian"


- name: stop accepting locale env vars from your client to the server
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^AcceptEnv LANG LC_(.+)"
    line: "#AcceptEnv LANG LC_\\1"
    backrefs: yes
  when: locale_stop
  register: sshd_config

# Restart SSH daemon on Debian/Ubuntu
- name: restart SSHd on Debian based distros, if necessary
  service: name=ssh state=reloaded